# Generated by Django 5.0.6 on 2024-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0001_initial'),
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='musician',
        ),
        migrations.AddField(
            model_name='album',
            name='musicians',
            field=models.ManyToManyField(related_name='albums', to='musician_app.musician'),
        ),
    ]
